// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbchheswoxbjfibouiyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiY2hoZXN3b3hiamZpYm91aXljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzMzQ5NTMsImV4cCI6MjA1NTkxMDk1M30.Sg_oTC2dJj7JKm4YkZV9zFNbuXK9WyEqzHbsKV8DxiA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);